"use client";
import {useState} from "react";
import {useAdmin} from "@/components/admin-shell";
import {allSections,type AdminSection} from "@/data/admin";
import {SectionContent} from "@/components/section-content";
import {AdminShell} from "@/components/admin-shell";

const kpis=[["Toplam Ciro","₺28.456.789","▲ %18,6 · Dün: ₺24.012.620","fa-chart-simple"],["Aktif Satıcı","12.842","▲ %9,3 · Dün: 11.740","fa-store"],["Aktif Müşteri","1.234.567","▲ %12,4 · Dün: 1.098.324","fa-users"],["Günlük Sipariş","24.657","▲ %21,7 · Dün: 20.255","fa-cart-shopping"],["Onay Bekleyen Ürün","5.432","▲ %5,8 · Dün: 5.135","fa-cube"],["Destek Talepleri","256","▲ %6,3 · Dün: 241","fa-headset"]];
const sellers=[["T","TeknoLife Elektronik","Elektronik · Başvuru: 9 May 2025, 10:23"],["M","ModaVitrin","Moda · Başvuru: 9 May 2025, 09:47"],["H","HomeComfort","Ev & Yaşam · Başvuru: 9 May 2025, 09:15"],["S","Sportiva","Spor & Outdoor · Başvuru: 9 May 2025, 08:56"]];
const rows=[["TeknoLife Elektronik","Elektronik","İncelemede","Bugün, 10:23"],["ModaVitrin","Moda","Bilgi Eksik","Bugün, 09:47"],["HomeComfort","Ev & Yaşam","Onaylandı","Dün, 17:12"],["Sportiva","Spor & Outdoor","İnceleniyor","Dün, 15:46"],["Petopia","Pet Shop","Aktif","8 May, 12:32"]];
function Btn({children,primary=false,onClick}:{children:React.ReactNode;primary?:boolean;onClick?:()=>void}){return <button className={`btn ${primary?"primary":""}`} onClick={onClick}>{children}</button>}
function Head({section}:{section:AdminSection}){const{openDrawer,notify}=useAdmin();return <div className="page-head"><div className="page-title"><h1>{section.title}</h1><p>{section.description}</p></div><div className="head-actions"><Btn onClick={()=>notify("Filtreler uygulandı")}><i className="fa-solid fa-filter"/>Filtrele</Btn><Btn primary onClick={()=>openDrawer(section.title)}><i className="fa-solid fa-plus"/>Yeni İşlem</Btn></div></div>}
function Status({section}:{section:AdminSection}){return <div className="status-board">{[["fa-hourglass-half",section.metric||"32",section.metricLabel||"İncelemede","yellow"],["fa-folder-open","14","Belge bekliyor","blue"],["fa-circle-check","18","Bugün onaylanan","green"],["fa-triangle-exclamation","6","Bilgi eksik / riskli","red"],["fa-key","11","Yetki açılacak",""]].map(x=><div className={`status-card ${x[3]}`} key={x[2]}><i className={`fa-solid ${x[0]}`}/><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div>}
function DataPanel({section}:{section:AdminSection}){const{openDrawer,notify}=useAdmin();return <div className="card"><div className="card-head"><h3>{section.title} Listesi</h3><span className="link">Son güncelleme: az önce</span></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Kayıt / Mağaza</th><th>Kategori</th><th>Durum</th><th>Güncelleme</th><th>İşlem</th></tr></thead><tbody>{rows.map(x=><tr key={x[0]}><td><b>{x[0]}</b></td><td>{x[1]}</td><td><span className={`pill ${x[2]==="Onaylandı"||x[2]==="Aktif"?"green":x[2]==="Bilgi Eksik"?"red":"yellow"}`}>{x[2]}</span></td><td>{x[3]}</td><td><button className="pill" onClick={()=>openDrawer(`${section.title} · ${x[0]}`)}>İncele</button> <button className="pill green" onClick={()=>notify("Kayıt onaylandı")}>Onayla</button></td></tr>)}</tbody></table></div></div>}
function Chart(){return <div className="card"><div className="card-head"><h3>Satış Performansı</h3><Btn>7 Günlük <i className="fa-solid fa-chevron-down"/></Btn></div><div className="card-body"><div className="chart"><div className="chart-meta"><span>Toplam Ciro<b>₺28.456.789</b></span><span>Sipariş Adedi<b>172.453</b></span></div><svg preserveAspectRatio="none" viewBox="0 0 620 185"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#ff4f30" stopOpacity=".22"/><stop offset="1" stopColor="#ff4f30" stopOpacity="0"/></linearGradient></defs><path d="M0,130 C70,92 110,104 150,92 C210,72 230,39 290,72 C340,96 385,98 430,72 C480,42 520,48 620,92 L620,185 L0,185 Z" fill="url(#g)"/><path d="M0,130 C70,92 110,104 150,92 C210,72 230,39 290,72 C340,96 385,98 430,72 C480,42 520,48 620,92" fill="none" stroke="#ff4f30" strokeWidth="5"/><path d="M0,150 C80,125 120,135 165,121 C230,98 255,75 305,102 C355,126 410,119 455,93 C510,60 550,82 620,112" fill="none" stroke="#ffb000" strokeWidth="3"/></svg><div className="chart-tooltip"><b>18 Ağustos 2026</b>Ciro: ₺5.742.310<br/>Sipariş: 33.842</div></div></div></div>}
function Sellers(){const{setActive,openDrawer}=useAdmin();return <div className="card"><div className="card-head"><h3>Onay Bekleyen Satıcılar</h3><button className="link" onClick={()=>setActive("sellers")}>Tümünü Gör</button></div><div className="card-body list">{sellers.map(x=><div className="row" key={x[1]}><div className="mini-logo">{x[0]}</div><div><div className="row-title">{x[1]}</div><div className="row-sub">{x[2]}</div></div><button className="pill" onClick={()=>openDrawer({type:"sellerDetail",record:x[1]})}>İncele</button></div>)}</div></div>}
function Tickets(){const{setActive}=useAdmin();return <div className="card"><div className="card-head"><h3>Son Destek Talepleri</h3><button className="link" onClick={()=>setActive("support")}>Tümünü Gör</button></div><div className="card-body list">{[["#STK-84521","İade / Para İadesi","Açık"],["#STK-84520","Kargo Gecikmesi","Açık"],["#STK-84519","Ürün Hasarlı Geldi","İnceleniyor"],["#STK-84518","Fatura Talebi","Yanıtlandı"]].map(x=><div className="row ticket-row" key={x[0]}><div className="pill">{x[0]}</div><div><div className="row-title">{x[1]}</div><div className="row-sub">Müşteri destek talebi</div></div><span className={`pill ${x[2]==="Yanıtlandı"?"green":x[2]==="İnceleniyor"?"yellow":"red"}`}>{x[2]}</span></div>)}</div></div>}
function Commission(){return <div className="card"><div className="card-head"><h3>Komisyon Kazançları</h3><span className="pill">Aylık</span></div><div className="card-body"><h2>₺4.562.317</h2><div className="donut-wrap"><div className="donut"/><div className="legend"><span><i/>Pazaryeri Komisyonu <b>₺2.848.921</b></span><span><i/>Reklam Gelirleri <b>₺854.132</b></span><span><i/>Hizmet Bedelleri <b>₺561.223</b></span><span><i/>Diğer Gelirler <b>₺298.041</b></span></div></div></div></div>}
function Categories(){return <div className="card"><div className="card-head"><h3>En Çok Satan Kategoriler</h3><span className="link">Tümünü Gör</span></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Kategori</th><th>Ciro</th><th>Pay</th></tr></thead><tbody>{[["Elektronik","₺8.456.123","%29,7"],["Moda","₺6.234.789","%21,9"],["Ev & Yaşam","₺4.568.214","%16,0"],["Kozmetik","₺3.214.567","%11,3"]].map(x=><tr key={x[0]}>{x.map(y=><td key={y}>{y}</td>)}</tr>)}</tbody></table></div></div>}
function Risk(){return <div className="card"><div className="card-head"><h3>Risk & Dolandırıcılık Uyarıları</h3></div><div className="card-body">{[["Şüpheli Yüksek İade Oranı","Yüksek"],["Anormal Sipariş Aktivitesi","Orta"],["Aynı Karttan Çoklu Sipariş","Orta"],["Fiyat Manipülasyonu Şüphesi","Düşük"]].map(x=><div className="risk-row danger" key={x[0]}><i className="fa-solid fa-triangle-exclamation"/><div><div className="row-title">{x[0]}</div><div className="row-sub">Otomatik risk kontrolü</div></div><span className="pill red">{x[1]}</span></div>)}</div></div>}
function Activity(){return <div className="card"><div className="card-head"><h3>Son Sistem Aktiviteleri</h3><span className="link">● Canlı Akış</span></div><div className="card-body activity">{[["fa-store","Yeni satıcı başvurusu: TeknoLife Elektronik"],["fa-check","Toplu ürün onayı: 58 ürün"],["fa-bullhorn","Kampanya yayınlandı: Büyük İndirim Günleri"],["fa-percent","Komisyon ödemesi yapıldı: Temmuz 2026"]].map(x=><div className="act" key={x[1]}><div className="mini-logo orange"><i className={`fa-solid ${x[0]}`}/></div><div><div className="row-title">{x[1]}</div><div className="row-sub">18 Ağustos 2026 · Yönetim Paneli</div></div><i className="fa-solid fa-chevron-right"/></div>)}</div></div>}
function Overview(){const{setActive,openDrawer,notify}=useAdmin();return <><div className="page-head"><div className="page-title"><h1>Hoş geldiniz, Admin 👋</h1><p>Platform performansını aşağıdan takip edebilirsiniz.</p></div><div className="head-actions"><Btn><i className="fa-regular fa-calendar"/>18 Ağustos 2026, Salı</Btn><Btn onClick={()=>notify("Rapor dışa aktarıldı")}><i className="fa-solid fa-download"/>Dışa Aktar</Btn></div></div><div className="kpi-grid">{kpis.map((x,i)=><div className={`kpi ${i===4?"yellow":i===5?"purple":""}`} key={x[0]}><i className={`fa-solid ${x[3]}`}/><h4>{x[0]}</h4><div className="num">{x[1]}</div><div className={`trend ${i>3?"red":""}`}>{x[2]}</div></div>)}</div><div className="quickbar"><strong>Hızlı İşlemler</strong><Btn primary onClick={()=>openDrawer({type:"sellerApprove"})}>Satıcı Onayla</Btn><Btn primary onClick={()=>openDrawer({type:"campaign"})}>Kampanya Yayınla</Btn><Btn primary onClick={()=>openDrawer({type:"announcement"})}>Duyuru Oluştur</Btn><Btn onClick={()=>setActive("approvals")}>Toplu Ürün Onayla</Btn><Btn onClick={()=>openDrawer({type:"coupon"})}>Kupon Oluştur</Btn><Btn onClick={()=>setActive("reports")}>Rapor Oluştur</Btn></div><div className="grid-3"><Chart/><Sellers/><Tickets/></div><div className="grid-3"><Commission/><Categories/><Risk/></div><Activity/></>}
function Workflow({section}:{section:AdminSection}){return <><Status section={section}/><div className="workflow">{["Başvuru Alındı","Ön Kontrol","Evrak Kontrolü","Yetkilendirme","Aktif Kayıt"].map((x,i)=><div className="workflow-step" key={x}><b><i>{i+1}</i>{x}</b><span>Gerekli bilgiler standart kurallara göre kontrol edilir.</span></div>)}</div><DataPanel section={section}/></>}
function Modules({section}:{section:AdminSection}){const{openDrawer}=useAdmin();return <div className="module-grid">{[["fa-chart-pie","Performans Özeti"],["fa-file-export","Rapor ve Dışa Aktarım"],["fa-sliders","Görünüm Kuralları"],["fa-clock-rotate-left","Planlama ve Geçmiş"],["fa-user-shield","Yetki Yönetimi"],["fa-circle-check","Yayın Kontrolü"]].map(x=><div className="module-card" key={x[1]}><div className="big-icon"><i className={`fa-solid ${x[0]}`}/></div><h3>{x[1]}</h3><p>{section.title} için ayrıntılı yönetim seçeneklerini ve değişiklik geçmişini görüntüleyin.</p><Btn onClick={()=>openDrawer(`${section.title} · ${x[1]}`)}>Yönet <i className="fa-solid fa-arrow-right"/></Btn></div>)}</div>}
function Settings({section}:{section:AdminSection}){const[open,setOpen]=useState(0);const{notify}=useAdmin();return <div className="grid-2"><div className="card"><div className="card-head"><h3>{section.title} Kuralları</h3></div><div className="card-body">{["Görünüm ve yayın ayarları","Sıralama ve öncelik kuralları","Yetkilendirme ve güvenlik","Bildirim tercihleri"].map((x,i)=><div className={`accordion ${open===i?"open":""}`} key={x}><button className="acc-head" onClick={()=>setOpen(open===i?-1:i)}>{x}<i className="fa-solid fa-chevron-down"/></button><div className="acc-body"><div className="form-grid"><label className="field">Durum<select><option>Aktif</option><option>Pasif</option></select></label><label className="field">Öncelik<input defaultValue={i+1}/></label></div></div></div>)}</div></div><div className="card"><div className="card-head"><h3>Canlı Önizleme</h3></div><div className="card-body"><div className="info-strip"><i className="fa-solid fa-circle-info"/><div><strong>Yayın kontrolü</strong><p>Değişiklikler kaydedildikten sonra web ve mobil alanlarına aktarılır.</p></div></div><label className="field">Yönetici Notu<textarea placeholder="Değişikliğin açıklamasını yazın"/></label><Btn primary onClick={()=>notify("Ayarlar kaydedildi")}>Değişiklikleri Kaydet</Btn></div></div></div>}
function AdminContent(){const{active}=useAdmin();const section=allSections.find(x=>x.id===active)||allSections[0];return <div className="content"><section className="section active">{section.kind==="overview"?<Overview/>:<SectionContent section={section}/>}</section></div>}
export default function AdminPage(){return <AdminShell><AdminContent/></AdminShell>}
