"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useAdmin } from "./admin-shell";

type Status = "draft" | "submitted" | "under_review" | "revision_requested" | "approved" | "rejected";
type DocumentStatus = "pending" | "under_review" | "complete" | "missing";
type Checklist = { store_name_valid:boolean; authorized_person_verified:boolean; contact_verified:boolean; company_verified:boolean; documents_complete:boolean; iban_verified:boolean };
type Application = { id:string; applicant_user_id:string; business_type:string; legal_name:string; tax_number:string|null; store_name:string; contact_email:string; contact_phone:string|null; authorized_name:string|null; sales_category:string|null; iban:string|null; preferred_shipping_company:string|null; document_status:DocumentStatus; missing_field:string|null; review_checklist:Partial<Checklist>|null; status:Status; admin_note:string|null; submitted_at:string|null; reviewed_at:string|null; created_at:string; updated_at:string };
type Seller = { id:string; legal_name:string; status:string; approved_application_id:string|null };
type Store = { id:string; name:string; slug:string; status:string; created_at:string; sellers:Seller|Seller[] };
type DrawerMode = "review"|"missing"|"detail";

const defaultChecklist:Checklist={store_name_valid:false,authorized_person_verified:false,contact_verified:false,company_verified:false,documents_complete:false,iban_verified:false};
const checklistLabels:[keyof Checklist,string][]=[["store_name_valid","Mağaza adı uygun"],["authorized_person_verified","Yetkili doğrulandı"],["contact_verified","Telefon/e-posta doğrulandı"],["company_verified","Vergi/şirket bilgisi incelendi"],["documents_complete","Evraklar tamam"],["iban_verified","IBAN kontrol edildi"]];
const businessLabels:Record<string,string>={individual:"Bireysel",sole_proprietorship:"Şahıs",limited:"Limited Şirket",corporation:"Anonim Şirket"};
const statusLabels:Record<Status,string>={draft:"Taslak",submitted:"Başvuru Alındı",under_review:"İncelemede",revision_requested:"Bilgi Eksik",approved:"Onaylandı",rejected:"Reddedildi"};
const statusTones:Record<Status,string>={draft:"blue",submitted:"yellow",under_review:"yellow",revision_requested:"blue",approved:"green",rejected:"red"};
const documentLabels:Record<DocumentStatus,string>={pending:"Bekliyor",under_review:"Evrak Kontrol",complete:"Tamam",missing:"Eksik"};
const workflow=[["Başvuru Alındı","Satıcı formu ve temel mağaza bilgileri sisteme düşer."],["Ön Kontrol","Mağaza adı, kategori, telefon/e-posta ve şirket türü kontrol edilir."],["Evrak Kontrolü","Mağaza türüne göre zorunlu belgeler onaylanır veya eksik istenir."],["Yetkilendirme","Ürün yükleme, kampanya ve finans ekranları kademeli açılır."],["Aktif Mağaza","Satıcı paneli tam yetkiyle açılır ve log kaydı oluşur."]];

export function AdminSellerManagement(){
 const {notify}=useAdmin();
 const [applications,setApplications]=useState<Application[]>([]),[stores,setStores]=useState<Store[]>([]);
 const [selectedId,setSelectedId]=useState<string|null>(null),[filterOpen,setFilterOpen]=useState(false),[filter,setFilter]=useState<Status|"all">("all"),[drawer,setDrawer]=useState<DrawerMode|null>(null);
 const [note,setNote]=useState(""),[missingField,setMissingField]=useState("IBAN Belgesi"),[checklist,setChecklist]=useState<Checklist>(defaultChecklist),[documentStatus,setDocumentStatus]=useState<DocumentStatus>("pending");
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/admin/seller-applications",{cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.error||"Satıcı yönetimi verileri alınamadı.");setApplications(result.applications||[]);setStores(result.stores||[]);setSelectedId(current=>current||result.applications?.find((item:Application)=>["under_review","submitted"].includes(item.status))?.id||result.applications?.[0]?.id||null);}catch(error){notify(error instanceof Error?error.message:"Satıcı yönetimi verileri alınamadı.");}finally{setLoading(false);}},[notify]);
 useEffect(()=>void load(),[load]);
 const selected=applications.find(item=>item.id===selectedId)||null;
 const queue=useMemo(()=>applications.filter(item=>item.status!=="approved"&&(filter==="all"||item.status===filter)),[applications,filter]);
 const openDrawer=(application:Application,mode:DrawerMode)=>{setSelectedId(application.id);setDrawer(mode);setNote(application.admin_note||"");setMissingField(application.missing_field||"IBAN Belgesi");setDocumentStatus(application.document_status);setChecklist({...defaultChecklist,...(application.review_checklist||{})});};
 const request=async(action:"review"|"approve"|"request_revision"|"reject"|"update_review")=>{if(!selected)return;if(["request_revision","reject"].includes(action)&&note.trim().length<3)return notify("Satıcıya gidecek açıklamayı yazın.");setSaving(true);try{if(action==="approve"){const saveResponse=await fetch(`/api/admin/seller-applications/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update_review",note,checklist,documentStatus})}),saveResult=await saveResponse.json();if(!saveResponse.ok)throw new Error(saveResult.error||"Kontrol listesi kaydedilemedi.");}const body=action==="update_review"?{action,note,checklist,documentStatus}:action==="request_revision"?{action,note,missingField}:{action,note:note||undefined};const response=await fetch(`/api/admin/seller-applications/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error||"İşlem tamamlanamadı.");notify(`${selected.store_name} başvurusu güncellendi.`);window.dispatchEvent(new Event("biseyeksik:navigation-counts"));setDrawer(null);await load();}catch(error){notify(error instanceof Error?error.message:"İşlem tamamlanamadı.");}finally{setSaving(false);}};
 const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"-",today=new Date().toDateString();
 const stats=[["İncelemede başvuru",applications.filter(x=>["submitted","under_review"].includes(x.status)).length,"fa-hourglass-half","yellow"],["Evrak bekleniyor",applications.filter(x=>x.document_status!=="complete"&&!["approved","rejected"].includes(x.status)).length,"fa-folder-open","blue"],["Bugün onaylanan",applications.filter(x=>x.status==="approved"&&x.reviewed_at&&new Date(x.reviewed_at).toDateString()===today).length,"fa-circle-check","green"],["Bilgi eksik / riskli",applications.filter(x=>["revision_requested","rejected"].includes(x.status)).length,"fa-triangle-exclamation","red"],["Yetki açılacak mağaza",applications.filter(x=>x.status==="under_review").length,"fa-key",""]] as const;
 return <>
  <div className="page-head"><div className="page-title"><h1>Satıcı Yönetimi</h1><p>Başvuru, onay, eksik bilgi, evrak ve mağaza yetkilendirme sürecini tek ekrandan yönetin.</p></div><div className="head-actions seller-head-actions"><div className="seller-filter-wrap"><button className="btn" onClick={()=>setFilterOpen(value=>!value)}><i className="fa-solid fa-filter"/> Filtrele</button>{filterOpen&&<select value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="all">Tüm başvurular</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>}</div><button className="btn primary" onClick={()=>selected?openDrawer(selected,"review"):notify("Onaylanacak başvuru bulunmuyor.")}><i className="fa-solid fa-user-plus"/> Yeni Satıcı Onayla</button></div></div>
  <div className="status-board">{stats.map(([label,value,icon,tone])=><div className={`status-card ${tone}`} key={label}><i className={`fa-solid ${icon}`}/><strong>{value}</strong><span>{label}</span></div>)}</div>
  <div className="workflow">{workflow.map(([title,text],index)=><div className="workflow-step" key={title}><b><i>{index+1}</i>{title}</b><span>{text}</span></div>)}</div>
  <div className="seller-review-grid">
   <section className="card content-table seller-queue"><div className="card-head"><h3>Başvuru Kuyruğu</h3><span className="seller-count">{queue.length} başvuru</span></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Mağaza</th><th>Tür / Kategori</th><th>Başvuru Durumu</th><th>Evrak</th><th>İşlem</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="seller-empty">Başvurular yükleniyor...</td></tr>:queue.length?queue.map(item=><tr key={item.id} className={selectedId===item.id?"selected":""} onClick={()=>setSelectedId(item.id)}><td><b>{item.store_name}</b><small>{item.authorized_name||item.legal_name} · {formatDate(item.submitted_at||item.created_at)}</small></td><td>{businessLabels[item.business_type]||item.business_type} · {item.sales_category||"Kategori yok"}</td><td><span className={`pill ${statusTones[item.status]}`}>{statusLabels[item.status]}</span></td><td><span className={`pill ${item.document_status==="complete"?"green":item.document_status==="missing"?"red":"yellow"}`}>{item.missing_field||documentLabels[item.document_status]}</span></td><td className="table-actions"><button onClick={event=>{event.stopPropagation();openDrawer(item,item.status==="revision_requested"?"missing":"review");}}>{item.status==="under_review"?"İncele":"Detay"}</button>{item.status==="submitted"&&<button onClick={event=>{event.stopPropagation();openDrawer(item,"review");}}>İncele</button>}{item.status==="under_review"&&<button onClick={event=>{event.stopPropagation();openDrawer(item,"review");}}>Onayla</button>}</td></tr>):<tr><td colSpan={5} className="seller-empty">Başvuru bulunmuyor.</td></tr>}</tbody></table></div></section>
   <section className="card seller-checklist-card"><div className="card-head"><h3>Başvuru Detay Checklist</h3><span className="seller-count">Standart kontrol</span></div><div className="card-body">{selected?<><div className="seller-rule"><i className="fa-solid fa-circle-info"/><div><b>Onay kuralı</b><p>Mağaza adı, yetkili bilgileri, doğrulama, evrak ve IBAN tamamlanmadan ürün yükleme yetkisi açılmaz.</p></div></div><div className="seller-checklist">{checklistLabels.map(([key,label])=>{const checked=Boolean(selected.review_checklist?.[key]);return <div key={key}><i className={`fa-solid ${checked?"fa-check":"fa-clock"}`}/>{label}</div>;})}</div><div className="seller-standard"><b>Admin açıklaması standardı:</b> Onay, red veya eksik evrak kararlarında satıcıya gidecek açıklama aynı bileşenle yazılır ve log ekranına düşer.</div><button className="btn primary" onClick={()=>openDrawer(selected,"missing")} disabled={!["under_review","revision_requested"].includes(selected.status)}><i className="fa-solid fa-paper-plane"/> Eksik Bilgi Talebi Gönder</button></>:<div className="seller-empty">Kontrol edilecek başvuru bulunmuyor.</div>}</div></section>
  </div>
  <section className="card content-table seller-active-table"><div className="card-head"><h3>Aktif Satıcı Listesi</h3><button className="link" onClick={()=>void load()}>Filtrele</button></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Mağaza</th><th>Kategori</th><th>Puan</th><th>Yetki</th><th>Son Kontrol</th><th>Durum</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="seller-empty">Satıcılar yükleniyor...</td></tr>:stores.length?stores.map(store=>{const seller=Array.isArray(store.sellers)?store.sellers[0]:store.sellers,application=applications.find(item=>item.id===seller?.approved_application_id);return <tr key={store.id}><td>{store.name}</td><td>{application?.sales_category||"-"}</td><td>-</td><td>Mağaza Sahibi</td><td>{formatDate(application?.reviewed_at||store.created_at)}</td><td><span className={`pill ${store.status==="active"?"green":store.status==="suspended"?"red":"yellow"}`}>{store.status==="active"?"Aktif":store.status==="suspended"?"Askıda":"Pasif"}</span></td></tr>;}):<tr><td colSpan={6} className="seller-empty">Aktif satıcı bulunmuyor.</td></tr>}</tbody></table></div></section>
  <div className={`drawer ${drawer?"active":""}`} onMouseDown={()=>!saving&&setDrawer(null)}><aside className="drawer-panel seller-review-drawer" onMouseDown={event=>event.stopPropagation()}>{selected&&<><div className="drawer-head"><h2>{drawer==="missing"?"Eksik Evrak / Bilgi Talebi":drawer==="detail"?"Satıcı Başvuru Detayı":"Satıcı Onay İşlemi"}</h2><button className="close" onClick={()=>setDrawer(null)}><i className="fa-solid fa-xmark"/></button></div>{drawer==="missing"?<MissingDrawer application={selected} missingField={missingField} setMissingField={setMissingField} note={note} setNote={setNote} saving={saving} send={()=>void request("request_revision")} close={()=>setDrawer(null)}/>:<ReviewDrawer application={selected} checklist={checklist} setChecklist={setChecklist} documentStatus={documentStatus} setDocumentStatus={setDocumentStatus} note={note} setNote={setNote} saving={saving} action={request} missing={()=>setDrawer("missing")}/>}</>}</aside></div>
 </>;
}

function MissingDrawer({application,missingField,setMissingField,note,setNote,saving,send,close}:{application:Application;missingField:string;setMissingField:(v:string)=>void;note:string;setNote:(v:string)=>void;saving:boolean;send:()=>void;close:()=>void}){return <div className="seller-drawer-card"><div className="big-icon"><i className="fa-solid fa-folder-open"/></div><h3>Eksik Evrak / Bilgi Talebi</h3><p>Bu mesaj satıcı panelindeki Evraklarım ekranında admin açıklaması olarak görünür.</p><div className="form-grid"><label className="field">Satıcı<input value={application.store_name} disabled/></label><label className="field">Eksik Alan<select value={missingField} onChange={e=>setMissingField(e.target.value)}>{["IBAN Belgesi","Vergi Belgesi","Yetkili Bilgisi","İletişim Bilgisi","Şirket Evrakı","Diğer"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field full">Satıcıya Gidecek Açıklama<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Eksik veya düzeltilmesi gereken bilgiyi açıklayın."/></label></div><div className="form-actions"><button className="btn primary" disabled={saving} onClick={send}><i className="fa-solid fa-paper-plane"/> Talebi Gönder</button><button className="btn" onClick={close}>Vazgeç</button></div></div>}
function ReviewDrawer({application,checklist,setChecklist,documentStatus,setDocumentStatus,note,setNote,saving,action,missing}:{application:Application;checklist:Checklist;setChecklist:React.Dispatch<React.SetStateAction<Checklist>>;documentStatus:DocumentStatus;setDocumentStatus:(v:DocumentStatus)=>void;note:string;setNote:(v:string)=>void;saving:boolean;action:(v:"review"|"approve"|"request_revision"|"reject"|"update_review")=>Promise<void>;missing:()=>void}){return <div className="seller-drawer-card"><div className="big-icon"><i className="fa-solid fa-store"/></div><h3>{application.store_name}</h3><p>Başvuru bilgileri, evrak durumu, IBAN/kargo bilgisi ve onay checklist’i tek ekranda kontrol edilir.</p><dl className="seller-review-details"><dt>Yetkili</dt><dd>{application.authorized_name||application.legal_name}</dd><dt>Mağaza Türü</dt><dd>{businessLabels[application.business_type]||application.business_type}</dd><dt>Satış Kategorisi</dt><dd>{application.sales_category||"Belirtilmedi"}</dd><dt>E-posta / Telefon</dt><dd>{application.contact_email} · {application.contact_phone||"-"}</dd><dt>IBAN</dt><dd>{application.iban||"Belirtilmedi"}</dd><dt>Kargo Firması</dt><dd>{application.preferred_shipping_company||"Belirtilmedi"}</dd></dl><div className="seller-drawer-checklist">{checklistLabels.map(([key,label])=><button key={key} disabled={application.status!=="under_review"} className={checklist[key]?"checked":""} onClick={()=>setChecklist(current=>({...current,[key]:!current[key]}))}><i className={`fa-solid ${checklist[key]?"fa-check":"fa-clock"}`}/>{label}</button>)}</div><label className="field">Evrak Durumu<select disabled={application.status!=="under_review"} value={documentStatus} onChange={e=>setDocumentStatus(e.target.value as DocumentStatus)}><option value="pending">Bekliyor</option><option value="under_review">İnceleniyor</option><option value="complete">Tamam</option><option value="missing">Eksik</option></select></label><label className="field">Admin Açıklaması<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Başvuru değerlendirme açıklaması"/></label><div className="form-actions seller-drawer-actions">{application.status==="submitted"&&<button className="btn primary" disabled={saving} onClick={()=>void action("review")}><i className="fa-solid fa-magnifying-glass"/> İncelemeye Al</button>}{application.status==="under_review"&&<><button className="btn primary" disabled={saving} onClick={()=>void action("approve")}><i className="fa-solid fa-check"/> Onayla</button><button className="btn" disabled={saving} onClick={missing}><i className="fa-solid fa-folder-open"/> Eksik Evrak İste</button><button className="btn" disabled={saving} onClick={()=>void action("update_review")}><i className="fa-solid fa-clock"/> Beklet / Kaydet</button><button className="btn danger" disabled={saving} onClick={()=>void action("reject")}><i className="fa-solid fa-xmark"/> Reddet</button></>}</div></div>}
