"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
type Rule={id:string;category_name:string;max_installments:number;fee_mode:string;fee_rate:number;minimum_cart_total:number;status:string;seller_note:string|null;published_at:string|null};
type Request={id:string;category_name:string;note:string;status:string;admin_note:string|null;created_at:string;stores:{name:string}|null};
const statusText:Record<string,string>={active:"Aktif",passive:"Pasif",limited:"Kısıtlı",pending:"Bekliyor",reviewing:"İnceleniyor",resolved:"Çözüldü",rejected:"Reddedildi"};
export function AdminInstallments(){
 const[rules,setRules]=useState<Rule[]>([]),[requests,setRequests]=useState<Request[]>([]),[editing,setEditing]=useState<Rule|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[preview,setPreview]=useState({category:"",price:10000});
 const load=useCallback(async()=>{const r=await fetch("/api/admin/installments"),j=await r.json();if(r.ok){setRules(j.rules||[]);setRequests(j.requests||[]);setError("")}else setError(j.error)},[]);useEffect(()=>{void load()},[load]);
 const stats=useMemo(()=>({active:rules.filter(x=>x.status==="active").length,max:rules.reduce((n,x)=>Math.max(n,x.max_installments),0),fee:rules.filter(x=>x.status==="active").reduce((n,x,_,a)=>n+Number(x.fee_rate)/a.length,0),requests:requests.filter(x=>["pending","reviewing"].includes(x.status)).length}),[rules,requests]);
 const shown=rules.find(x=>x.category_name.toLocaleLowerCase("tr-TR")===preview.category.trim().toLocaleLowerCase("tr-TR"));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),r=await fetch("/api/admin/installments",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing?.id,categoryName:f.categoryName,maxInstallments:Number(f.maxInstallments),feeMode:f.feeMode,feeRate:Number(f.feeRate),minimumCartTotal:Number(f.minimumCartTotal),status:f.status,sellerNote:f.sellerNote})}),j=await r.json();if(!r.ok){setError(j.error);return}setEditing(null);setMessage("Taksit kuralı kaydedildi ve yayınlandı.");await load()}
 async function decide(id:string,status:"reviewing"|"resolved"|"rejected"){const r=await fetch("/api/admin/installments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:id,status})}),j=await r.json();if(!r.ok){setError(j.error);return}await load()}
 return <><div className="page-head"><div className="page-title"><h1>Taksit Yönetimi <i className="fa-solid fa-circle-check backend-tick"/></h1><p>Kategori bazlı maksimum taksit, vade farkı, minimum sepet ve anasite/ödeme ekranı görünümünü yönetin.</p></div></div>
 <div className="status-board"><div className="status-card"><strong>{stats.active}</strong><span>Aktif Kategori</span></div><div className="status-card blue"><strong>{stats.max}</strong><span>En Yüksek Taksit</span></div><div className="status-card green"><strong>%{stats.fee.toLocaleString("tr-TR",{maximumFractionDigits:1})}</strong><span>Ortalama Vade Farkı</span></div><div className="status-card yellow"><strong>{stats.requests}</strong><span>Satıcı Talebi</span></div></div>
 {error&&<div className="admin-inline-error">{error}</div>}{message&&<div className="info-strip">{message}</div>}
 <div className="grid-2"><form className="card content-form" onSubmit={save} key={editing?.id||"new"}><div className="card-head"><h3>Kural Oluştur / Güncelle</h3><button type="button" className="link" onClick={()=>setEditing(null)}>Formu Temizle</button></div><div className="card-body"><div className="info-strip"><i className="fa-solid fa-circle-info"/><div><strong>Öncelik</strong><p>Aktif kategori kuralı ürün detayında ve ödeme ekranında gösterilir.</p></div></div><div className="form-grid"><label className="field">Kategori<input name="categoryName" required defaultValue={editing?.category_name||""}/></label><label className="field">Maksimum Taksit<select name="maxInstallments" defaultValue={editing?.max_installments||6}>{[1,3,6,9,12].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Vade Farkı Tipi<select name="feeMode" defaultValue={editing?.fee_mode||"none"}><option value="none">Vade farksız</option><option value="rate">Oranlı vade farkı</option></select></label><label className="field">Vade Farkı Oranı (%)<input name="feeRate" type="number" min="0" max="100" step="0.1" defaultValue={editing?.fee_rate||0}/></label><label className="field">Minimum Sepet Tutarı<input name="minimumCartTotal" type="number" min="0" step="0.01" defaultValue={editing?.minimum_cart_total||0}/></label><label className="field">Durum<select name="status" defaultValue={editing?.status||"active"}><option value="active">Aktif</option><option value="passive">Pasif</option><option value="limited">Kısıtlı</option></select></label><label className="field full">Satıcıya Gösterilecek Açıklama<textarea name="sellerNote" defaultValue={editing?.seller_note||""}/></label></div><button className="btn primary"><i className="fa-solid fa-save"/> Kuralı Kaydet</button></div></form>
 <div className="card"><div className="card-head"><h3>Ödeme Ekranı Önizlemesi</h3><span className="link">Canlı hesaplama</span></div><div className="card-body"><div className="form-grid"><label className="field">Örnek Kategori<input value={preview.category} onChange={e=>setPreview(v=>({...v,category:e.target.value}))}/></label><label className="field">Örnek Ürün Tutarı<input type="number" value={preview.price} onChange={e=>setPreview(v=>({...v,price:Number(e.target.value)}))}/></label></div>{shown?[1,3,6,9,12].filter(x=>x<=shown.max_installments).map(x=>{const total=preview.price*(1+(shown.fee_mode==="rate"&&x>1?Number(shown.fee_rate)/100:0));return <div className="row" key={x}><b>{x} Taksit</b><span>₺{(total/x).toLocaleString("tr-TR",{maximumFractionDigits:2})} / ay</span></div>}):<div className="empty-mini-state">Bu kategori için yayınlanmış kural bulunmuyor.</div>}</div></div></div>
 <div className="grid-2"><div className="card content-table"><div className="card-head"><h3>Kategori Bazlı Taksit Kuralları</h3><button className="link" onClick={()=>void load()}>Yenile</button></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Kategori</th><th>Maks.</th><th>Vade Farkı</th><th>Min. Sepet</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{rules.length?rules.map(x=><tr key={x.id}><td><b>{x.category_name}</b></td><td>{x.max_installments} taksit</td><td>{x.fee_mode==="rate"?`%${x.fee_rate}`:"Vade farksız"}</td><td>₺{Number(x.minimum_cart_total).toLocaleString("tr-TR")}</td><td><span className={`pill ${x.status==="active"?"green":x.status==="limited"?"yellow":"red"}`}>{statusText[x.status]}</span></td><td><button className="pill" onClick={()=>setEditing(x)}>Düzenle</button></td></tr>):<tr><td colSpan={6}>Henüz taksit kuralı bulunmuyor.</td></tr>}</tbody></table></div></div>
 <div className="card"><div className="card-head"><h3>Satıcı Talepleri / Bilgilendirme</h3><span className="link">{stats.requests} açık</span></div><div className="card-body list">{requests.length?requests.map(x=><div className="row" key={x.id}><div><b>{x.stores?.name||"Satıcı"} · {x.category_name}</b><div className="row-sub">{x.note}</div></div><span className="pill blue">{statusText[x.status]}</span>{x.status==="pending"&&<button className="pill" onClick={()=>void decide(x.id,"reviewing")}>İncele</button>}{x.status==="reviewing"&&<button className="pill" onClick={()=>void decide(x.id,"resolved")}>Çöz</button>}</div>):<div className="empty-mini-state">Satıcı bilgi talebi bulunmuyor.</div>}</div></div></div></>;
}
