"use client";
import { useCallback, useEffect, useState } from "react";
type Item = { id: string; question?: string; answer?: string | null; rating?: number; title?: string | null; body?: string | null; catalog_products: { title: string } | null; stores: { name: string } | null };
export function AdminProductFeedback() {
  const [questions, setQuestions] = useState<Item[]>([]), [reviews, setReviews] = useState<Item[]>([]), [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/product-feedback"), result = await response.json(); if (response.ok) { setQuestions(result.questions || []); setReviews(result.reviews || []); setError(""); } else setError(result.error || "İçerikler alınamadı."); }, []);
  useEffect(() => { void load(); }, [load]);
  async function decide(contentType: "question" | "review", contentId: string, decision: "published" | "rejected") { const response = await fetch("/api/admin/product-feedback", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contentType, contentId, decision }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } await load(); }
  const rows = [...questions.map(item => ({ ...item, type: "question" as const })), ...reviews.map(item => ({ ...item, type: "review" as const }))];
  return <div className="card content-table"><div className="card-head"><h3>Ürün İçerik Onayları </h3><span className="link">{rows.length} bekleyen</span></div>{error && <div className="admin-inline-error">{error}</div>}<div className="card-body table-scroll"><table className="table"><thead><tr><th>Tür</th><th>Ürün / Mağaza</th><th>İçerik</th><th>İşlem</th></tr></thead><tbody>{rows.length ? rows.map(item => <tr key={`${item.type}-${item.id}`}><td>{item.type === "question" ? "Soru / Yanıt" : `${item.rating} Yıldız`}</td><td><b>{item.catalog_products?.title || "Ürün"}</b><div className="row-sub">{item.stores?.name || "Mağaza"}</div></td><td>{item.question || item.title || item.body || "-"}{item.answer && <div className="row-sub">Yanıt: {item.answer}</div>}</td><td className="table-actions"><button onClick={() => void decide(item.type, item.id, "published")}>Yayınla</button><button onClick={() => void decide(item.type, item.id, "rejected")}>Reddet</button></td></tr>) : <tr><td colSpan={4}>Onay bekleyen ürün içeriği bulunmuyor.</td></tr>}</tbody></table></div></div>;
}
