"use client";
import { PointerEvent, useEffect, useMemo, useRef, useState } from "react";
import { AdminStorefrontContent } from "./admin-storefront-content";
import { RealStorefrontEditor } from "./real-storefront-editor";
type Viewport="web"|"mobile";type Block={id:string;title?:string;block_key?:string;block_type?:string;sort_order?:number;payload?:Record<string,unknown>};type LayoutItem=Block&{width:number;height:number;viewportOrder:number};
function dimensions(block:Block,viewport:Viewport){const layout=block.payload?.layout as Record<string,{order?:number;width?:number;height?:number}>|undefined;return{viewportOrder:layout?.[viewport]?.order??block.sort_order??0,width:layout?.[viewport]?.width??100,height:layout?.[viewport]?.height??(block.block_type==="hero"?190:132)}}
export function StorefrontLayoutEditor({blocks,onSaved}:{blocks:Block[];onSaved:()=>Promise<void>}){const[viewport,setViewport]=useState<Viewport>("web"),[items,setItems]=useState<LayoutItem[]>([]),[selected,setSelected]=useState<string|null>(null),[dragged,setDragged]=useState<string|null>(null),[message,setMessage]=useState("");const stageRef=useRef<HTMLDivElement>(null);const source=useMemo(()=>blocks.filter(block=>viewport==="web"?block.payload?.web!==false:block.payload?.mobile!==false),[blocks,viewport]);useEffect(()=>setItems(source.map(block=>({...block,...dimensions(block,viewport)})).sort((a,b)=>a.viewportOrder-b.viewportOrder)),[source,viewport]);
function drop(targetId:string){if(!dragged||dragged===targetId)return;setItems(current=>{const next=[...current],from=next.findIndex(item=>item.id===dragged),to=next.findIndex(item=>item.id===targetId),[moving]=next.splice(from,1);next.splice(to,0,moving);return next});setDragged(null)}
function resize(event:PointerEvent<HTMLButtonElement>,id:string){event.preventDefault();event.stopPropagation();const item=items.find(value=>value.id===id),stage=stageRef.current;if(!item||!stage)return;const startX=event.clientX,startY=event.clientY,startWidth=item.width,startHeight=item.height,stageWidth=stage.clientWidth;event.currentTarget.setPointerCapture(event.pointerId);const move=(next:globalThis.PointerEvent)=>setItems(current=>current.map(value=>value.id===id?{...value,width:Math.max(40,Math.min(100,startWidth+(next.clientX-startX)/stageWidth*100)),height:Math.max(72,Math.min(640,startHeight+next.clientY-startY))}:value));const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop)}
async function save(){setMessage("");const response=await fetch("/api/admin/storefront-content",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"layout",viewport,items:items.map((item,index)=>({id:item.id,sortOrder:index+1,width:Math.round(item.width),height:Math.round(item.height)}))})}),result=await response.json();if(!response.ok){setMessage(result.error);return}setMessage(`${viewport==="web"?"Web":"Mobil"} düzeni kaydedildi.`);await onSaved()}
return <section className="visual-editor card"><div className="visual-editor-head"><div><h3>Görsel Ana Sayfa Düzenleyici</h3><p>Alanları tutup taşıyın; sağ alt köşeden genişlik ve yüksekliği ayarlayın.</p></div><div className="visual-editor-actions"><div className="view-switch"><button className={viewport==="web"?"active":""} onClick={()=>setViewport("web")}><i className="fa-solid fa-display"/> Web</button><button className={viewport==="mobile"?"active":""} onClick={()=>setViewport("mobile")}><i className="fa-solid fa-mobile-screen"/> Mobil</button></div><button className="btn primary" onClick={()=>void save()}><i className="fa-solid fa-floppy-disk"/> Düzeni Kaydet</button></div></div>{message&&<div className="layout-message">{message}</div>}<div className={viewport==="mobile"?"layout-device phone":"layout-device desktop"}>{viewport==="mobile"&&<div className="phone-speaker"/>}<div className="layout-browser-bar"><span/><span/><span/><b>bişeyeksik</b></div><div className="layout-stage" ref={stageRef}>{items.length?items.map(item=><article key={item.id} style={{width:`${item.width}%`,height:item.height}} className={`layout-block ${selected===item.id?"selected":""}`} draggable onDragStart={()=>setDragged(item.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>drop(item.id)} onClick={()=>setSelected(item.id)}><div className="layout-drag"><i className="fa-solid fa-grip-vertical"/><span><b>{item.title||item.block_key}</b><small>{item.block_type}</small></span></div><div className="layout-placeholder"><i className={`fa-solid ${item.block_type==="hero"?"fa-image":"fa-layer-group"}`}/><span>{Math.round(item.width)}% × {Math.round(item.height)} px</span></div><button className="layout-resize" aria-label="Ölçülendir" onPointerDown={event=>resize(event,item.id)}><i className="fa-solid fa-up-right-and-down-left-from-center"/></button></article>):<div className="layout-empty">Düzenlenecek yayınlanmış vitrin bloğu bulunmuyor.</div>}</div></div></section>}
export function AdminHomeLayout(){return <><AdminStorefrontContent mode="block"/><RealStorefrontEditor/></>}
