"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { formatTL } from "@/data/catalog";

type OrderItem={id:string;product_title:string;variant_title:string;seller_name:string;product_image_url:string|null;quantity:number;line_total:number;fulfillment_status:string};
type Order={id:string;order_number:string;status:string;payment_status:string;grand_total:number;placed_at:string|null;created_at:string;order_items:OrderItem[]};
type RequestItem={id:string;order_item_id:string;request_type:"cancellation"|"return";status:string;resolution_note:string|null};
const labels:Record<string,string>={created:"Oluşturuldu",awaiting_payment:"Ödeme Bekliyor",paid:"Ödendi",preparing:"Hazırlanıyor",partially_shipped:"Kısmen Kargolandı",shipped:"Kargolandı",delivered:"Teslim Edildi",cancelled:"İptal Edildi",refunded:"İade Edildi"};
const requestLabels:Record<string,string>={submitted:"Talep Alındı",under_review:"İnceleniyor",approved:"Onaylandı",rejected:"Reddedildi",completed:"Tamamlandı",withdrawn:"Geri Çekildi"};

export function CustomerOrders(){
 const[orders,setOrders]=useState<Order[]>([]),[requests,setRequests]=useState<RequestItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<{item:OrderItem;type:"cancellation"|"return"}|null>(null),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const[ordersResponse,requestsResponse]=await Promise.all([fetch("/api/customer/orders"),fetch("/api/customer/order-requests")]);const orderResult=await ordersResponse.json(),requestResult=await requestsResponse.json();if(ordersResponse.ok)setOrders(orderResult.orders||[]);else setError(orderResult.error||"Siparişler alınamadı.");if(requestsResponse.ok)setRequests(requestResult.requests||[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setSaving(true);const values=Object.fromEntries(new FormData(event.currentTarget).entries()),response=await fetch("/api/customer/order-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderItemId:selected.item.id,requestType:selected.type,reasonCode:values.reasonCode,explanation:values.explanation})}),result=await response.json();setSaving(false);if(!response.ok){setError(result.error||"Talep oluşturulamadı.");return}setSelected(null);setError("");await load()}
 if(loading)return <div className="account-panel"><p>Siparişler yükleniyor...</p></div>;
 if(!orders.length)return <div className="account-panel"><i className="fa-solid fa-box-open"/><h3>Henüz sipariş kaydı bulunmuyor</h3><p>Sipariş verdiğinizde güncel durumunu burada görebilirsiniz.</p></div>;
 return <>{error&&<div className="customer-auth-message">{error}</div>}<div className="customer-order-list">{orders.map(order=><article key={order.id}><header><div><strong>{order.order_number}</strong><small>{new Date(order.placed_at||order.created_at).toLocaleString("tr-TR")}</small></div><span className={`customer-order-status status-${order.status}`}>{labels[order.status]||order.status}</span></header><div className="customer-order-items">{order.order_items.map(item=>{const activeRequest=requests.find(request=>request.order_item_id===item.id&&["submitted","under_review","approved"].includes(request.status));return <div key={item.id}>{item.product_image_url?<Image src={item.product_image_url} width={64} height={64} alt={item.product_title}/>:<span className="customer-order-image"><i className="fa-solid fa-box"/></span>}<div><b>{item.product_title}</b><small>{item.seller_name} · {item.variant_title} · {item.quantity} adet</small>{activeRequest?<span className="customer-request-state">{activeRequest.request_type==="return"?"İade":"İptal"}: {requestLabels[activeRequest.status]||activeRequest.status}</span>:<span className="customer-order-actions">{!["shipped","delivered","cancelled","returned"].includes(item.fulfillment_status)&&<button onClick={()=>setSelected({item,type:"cancellation"})}>İptal Talebi</button>}{item.fulfillment_status==="delivered"&&<button onClick={()=>setSelected({item,type:"return"})}>İade Talebi</button>}</span>}</div><strong>{formatTL(Number(item.line_total))}</strong></div>})}</div><footer><span>Ödeme durumu: {order.payment_status==="pending"?"Bekliyor":"Ödendi"}</span><b>{formatTL(Number(order.grand_total))}</b></footer></article>)}</div>{selected&&<div className="modal-overlay" onClick={()=>setSelected(null)}><form className="customer-request-modal" onSubmit={submit} onClick={event=>event.stopPropagation()}><button type="button" className="popup-close" onClick={()=>setSelected(null)}>×</button><i className={`fa-solid ${selected.type==="return"?"fa-rotate-left":"fa-ban"}`}/><h2>{selected.type==="return"?"İade Talebi":"İptal Talebi"}</h2><p>{selected.item.product_title}</p><label>Talep Nedeni<select name="reasonCode" required defaultValue=""><option value="" disabled>Seçiniz</option>{(selected.type==="return"?["Ürün hasarlı","Yanlış ürün","Beklentimi karşılamadı","Diğer"]:["Yanlış ürün seçtim","Adres değişikliği","Siparişten vazgeçtim","Diğer"]).map(reason=><option key={reason}>{reason}</option>)}</select></label><label>Açıklama<textarea name="explanation" maxLength={1000}/></label><button className="customer-auth-submit" disabled={saving}>{saving?"Gönderiliyor":"Talebi Gönder"}</button></form></div>}</>;
}
