"use client";
import { FormEvent, useState } from "react";
import { CustomerAddresses } from "./customer-addresses";
type Props={email:string;displayName:string;phone:string};

export function CustomerAccount({email,displayName,phone}:Props){
 const[active,setActive]=useState("Profilim"),[editing,setEditing]=useState(false),[name,setName]=useState(displayName),[phoneValue,setPhone]=useState(phone),[message,setMessage]=useState("");
 async function save(event:FormEvent){event.preventDefault();const response=await fetch("/api/customer/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:name,phone:phoneValue})}),result=await response.json();setMessage(response.ok?"Profil güncellendi.":result.error||"Profil güncellenemedi.");if(response.ok)setEditing(false)}
 const initials=name.split(" ").filter(Boolean).slice(0,2).map(part=>part[0]?.toLocaleUpperCase("tr-TR")).join("")||"M";
 return <div className="container page account"><section className="account-header"><div>{initials}</div><span><h1>{name}</h1><p>{email}{phoneValue&&` · ${phoneValue}`}</p></span><button onClick={()=>setEditing(value=>!value)}>Profili Düzenle</button></section><div className="account-layout"><nav className="account-menu">{[["fa-user","Profilim"],["fa-box","Siparişlerim"],["fa-location-dot","Adreslerim"],["fa-gear","Ayarlar"]].map(item=><button className={active===item[1]?"active":""} onClick={()=>setActive(item[1])} key={item[1]}><i className={`fa-solid ${item[0]}`}/>{item[1]}<i className="fa-solid fa-chevron-right"/></button>)}<form action="/api/customer/logout" method="post"><button className="logout"><i className="fa-solid fa-right-from-bracket"/>Çıkış Yap</button></form></nav><section className="account-content"><h2>{active}{active==="Profilim"&&<i className="fa-solid fa-circle-check storefront-backend-tick" title="Backend bağlantısı tamamlandı"/>}{active==="Adreslerim"&&<i className="fa-solid fa-circle-check storefront-backend-tick" title="Backend bağlantısı tamamlandı"/>}</h2>{active==="Profilim"?<form className="customer-profile-form" onSubmit={save}><label>Ad Soyad<input value={name} onChange={event=>setName(event.target.value)} readOnly={!editing} required minLength={2}/></label><label>E-posta<input value={email} readOnly/></label><label>Telefon<input value={phoneValue} onChange={event=>setPhone(event.target.value)} readOnly={!editing} placeholder="05xx xxx xx xx"/></label>{editing&&<button>Değişiklikleri Kaydet</button>}{message&&<p>{message}</p>}</form>:active==="Adreslerim"?<CustomerAddresses/>:<div className="account-panel"><i className={`fa-solid ${active==="Siparişlerim"?"fa-box-open":"fa-gear"}`}/><h3>{active}</h3><p>{active==="Siparişlerim"?"Henüz sipariş kaydı bulunmuyor.":"Hesap ayarları bu alanda gösterilecek."}</p></div>}</section></div></div>
}
