import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createAuthServerClient } from "@/lib/supabase/server";
import { z } from "zod";

const decisionSchema=z.object({requestId:z.string().uuid(),decision:z.enum(["approve","reject"]),note:z.string().trim().min(3).max(1000)});

export async function GET(){const auth=await createAuthServerClient(),{data:{user}}=await auth.auth.getUser();if(!user)return NextResponse.json({error:"Oturum gerekli."},{status:401});const admin=createSupabaseAdminClient();let{data:member}=await admin.from("store_members").select("store_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!member){const{data:seller}=await admin.from("sellers").select("id").eq("owner_user_id",user.id).eq("status","active").maybeSingle();if(seller){const{data:store}=await admin.from("stores").select("id").eq("seller_id",seller.id).in("status",["active","passive"]).maybeSingle();member=store?{store_id:store.id}:null}}if(!member)return NextResponse.json({error:"Mağaza erişimi bulunamadı."},{status:403});const{data,error}=await admin.from("order_requests").select("id,request_type,reason_code,explanation,status,resolution_note,created_at,orders!inner(order_number),order_items!inner(product_title,variant_title,quantity)").eq("store_id",member.store_id).order("created_at",{ascending:false});if(error)return NextResponse.json({error:"Talepler alınamadı."},{status:500});return NextResponse.json({requests:data||[]})}
export async function PATCH(request:Request){const auth=await createAuthServerClient(),{data:{user}}=await auth.auth.getUser();if(!user)return NextResponse.json({error:"Oturum gerekli."},{status:401});const parsed=decisionSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Karar bilgilerini kontrol edin."},{status:400});const admin=createSupabaseAdminClient(),{error}=await admin.rpc("decide_order_request",{p_request_id:parsed.data.requestId,p_actor_user_id:user.id,p_decision:parsed.data.decision,p_note:parsed.data.note});if(error)return NextResponse.json({error:error.message.includes("access_denied")?"Bu talep için işlem yetkiniz bulunmuyor.":error.message.includes("already_decided")?"Talep daha önce sonuçlandırılmış.":"Talep sonuçlandırılamadı."},{status:409});return NextResponse.json({ok:true})}
