import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createAuthServerClient } from "@/lib/supabase/server";

const schema=z.object({name:z.string().trim().min(2).max(120),description:z.string().trim().max(2000),status:z.enum(["active","passive"])});
async function context(){const auth=await createAuthServerClient(),{data:{user}}=await auth.auth.getUser();if(!user)return null;const admin=createSupabaseAdminClient(),{data:seller}=await admin.from("sellers").select("id,legal_name,status").eq("owner_user_id",user.id).maybeSingle();if(!seller||seller.status!=="active")return null;const{data:store}=await admin.from("stores").select("id,name,description,status").eq("seller_id",seller.id).maybeSingle();return store?{admin,user,seller,store}:null}
export async function GET(){const current=await context();if(!current)return NextResponse.json({error:"Mağaza hesabı bulunamadı."},{status:403});return NextResponse.json({profile:{...current.store,authorizedName:typeof current.user.user_metadata?.display_name==="string"?current.user.user_metadata.display_name:current.seller.legal_name,email:current.user.email||""}})}
export async function PATCH(request:Request){const current=await context();if(!current)return NextResponse.json({error:"Mağaza hesabı bulunamadı."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Mağaza bilgilerini kontrol edin."},{status:400});const{data,error}=await current.admin.from("stores").update({name:parsed.data.name,description:parsed.data.description||null,status:parsed.data.status}).eq("id",current.store.id).select("id,name,description,status").single();if(error)return NextResponse.json({error:error.code==="23505"?"Bu mağaza adı zaten kullanılıyor.":"Mağaza profili güncellenemedi."},{status:error.code==="23505"?409:500});return NextResponse.json({ok:true,profile:data})}
