"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type Balance = { warehouse_id:string; offer_id:string; on_hand:number; reserved:number; available:number; updated_at:string; warehouses:{name:string}; seller_offers:{seller_sku:string;status:string;product_variants:{title:string;catalog_products:{title:string}}} };

export function SellerInventory() {
  const [items,setItems]=useState<Balance[]>([]), [selected,setSelected]=useState<Balance|null>(null), [quantity,setQuantity]=useState(0), [reason,setReason]=useState(""), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/inventory"),result=await response.json();if(response.ok){setItems(result.inventory||[]);setError("")}else setError(result.error||"Stok bilgileri alınamadı.");setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const totals=useMemo(()=>({onHand:items.reduce((sum,item)=>sum+item.on_hand,0),reserved:items.reduce((sum,item)=>sum+item.reserved,0),available:items.reduce((sum,item)=>sum+item.available,0),critical:items.filter(item=>item.available<=5).length}),[items]);
  const edit=(item:Balance)=>{setSelected(item);setQuantity(item.on_hand);setReason("");setError("")};
  const save=async()=>{if(!selected)return;setSaving(true);setError("");const response=await fetch("/api/inventory",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({warehouseId:selected.warehouse_id,offerId:selected.offer_id,quantity,reason})}),result=await response.json();setSaving(false);if(!response.ok){setError(result.error||"Stok güncellenemedi.");return}setSelected(null);await load()};

  return <>
    <div className="page-head"><div className="page-title"><h1>Stok Yönetimi </h1><p>Depo bakiyelerini, ayrılmış ve satışa hazır ürün adetlerini yönetin.</p></div><button className="btn" onClick={()=>void load()}><i className="fa-solid fa-rotate"/> Yenile</button></div>
    <div className="catalog-board"><article><i className="fa-solid fa-boxes-stacked"/><h4>Toplam Stok</h4><b>{totals.onHand}</b><span>Fiziksel ürün</span></article><article className="yellow"><i className="fa-solid fa-lock"/><h4>Ayrılmış</h4><b>{totals.reserved}</b><span>Sipariş için ayrılan</span></article><article className="green"><i className="fa-solid fa-box-open"/><h4>Satılabilir</h4><b>{totals.available}</b><span>Güncel kullanılabilir</span></article><article className="red"><i className="fa-solid fa-triangle-exclamation"/><h4>Kritik Stok</h4><b>{totals.critical}</b><span>5 adet ve altı</span></article></div>
    {error&&<div className="apply-error"><i className="fa-solid fa-circle-exclamation"/>{error}</div>}
    <div className="card"><div className="card-head"><h3>Depo Stokları</h3><span className="link">{items.length} teklif</span></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Ürün</th><th>SKU</th><th>Depo</th><th>Toplam</th><th>Ayrılmış</th><th>Satılabilir</th><th>İşlem</th></tr></thead><tbody>{loading&&<tr><td colSpan={7} className="empty-table-cell">Stoklar yükleniyor...</td></tr>}{!loading&&items.length===0&&<tr><td colSpan={7} className="empty-table-cell">Stok kaydı bulunmuyor.</td></tr>}{items.map(item=><tr key={`${item.warehouse_id}-${item.offer_id}`}><td><b>{item.seller_offers.product_variants.catalog_products.title}</b><div className="row-sub">{item.seller_offers.product_variants.title}</div></td><td>{item.seller_offers.seller_sku}</td><td>{item.warehouses.name}</td><td>{item.on_hand}</td><td>{item.reserved}</td><td><span className={`pill ${item.available<=5?"red":"green"}`}>{item.available}</span></td><td><button className="pill" onClick={()=>edit(item)}>Güncelle</button></td></tr>)}</tbody></table></div></div>
    {selected&&<div className="drawer active" onClick={()=>setSelected(null)}><div className="drawer-panel" onClick={event=>event.stopPropagation()}><div className="drawer-head"><h2>Stok Güncelle</h2><button onClick={()=>setSelected(null)} aria-label="Kapat"><i className="fa-solid fa-xmark"/></button></div><div className="info-strip"><i className="fa-solid fa-box"/><div><strong>{selected.seller_offers.product_variants.catalog_products.title}</strong><p>{selected.seller_offers.seller_sku} · {selected.warehouses.name}</p></div></div><div className="form-grid"><label className="field">Yeni Toplam Stok<input type="number" min={selected.reserved} value={quantity} onChange={event=>setQuantity(Number(event.target.value))}/></label><label className="field wide">Güncelleme Nedeni<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Örn. Depo sayımı güncellendi" maxLength={500}/></label></div>{error&&<div className="apply-error"><i className="fa-solid fa-circle-exclamation"/>{error}</div>}<div className="drawer-buttons"><button className="btn primary" disabled={saving||reason.trim().length<3} onClick={()=>void save()}>{saving?"Kaydediliyor...":"Stoku Kaydet"}</button><button className="btn" onClick={()=>setSelected(null)}>Vazgeç</button></div></div></div>}
  </>;
}
