"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Question = { id: string; question: string; answer: string | null; status: string; created_at: string; catalog_products: { title: string } | null };
export function SellerQuestions() {
  const [items, setItems] = useState<Question[]>([]), [selected, setSelected] = useState<Question | null>(null), [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/product-questions"), result = await response.json(); if (response.ok) { setItems(result.questions || []); setError(""); } else setError(result.error || "Sorular alınamadı."); }, []);
  useEffect(() => { void load(); }, [load]);
  async function answer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const answer = String(new FormData(event.currentTarget).get("answer") || ""); const response = await fetch("/api/product-questions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: selected.id, answer }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setSelected(null); await load(); }
  return <><div className="card content-table"><div className="card-head"><h3>Müşteri Soruları </h3><span className="link">{items.filter(item => !item.answer).length} bekleyen</span></div>{error && <div className="admin-inline-error">{error}</div>}<div className="card-body table-scroll"><table className="table"><thead><tr><th>Ürün</th><th>Soru</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{items.length ? items.map(item => <tr key={item.id}><td>{item.catalog_products?.title || "Ürün"}</td><td>{item.question}{item.answer && <div className="row-sub">Yanıtınız: {item.answer}</div>}</td><td><span className={`pill ${item.answer ? "green" : "yellow"}`}>{item.answer ? "İncelemede" : "Yanıt Bekliyor"}</span></td><td><button className="pill" onClick={() => setSelected(item)}>Yanıtla</button></td></tr>) : <tr><td colSpan={4}>Müşteri sorusu bulunmuyor.</td></tr>}</tbody></table></div></div>
  {selected && <div className="modal-overlay" onClick={() => setSelected(null)}><form className="seller-request-modal" onSubmit={answer} onClick={event => event.stopPropagation()}><h2>Müşteri Sorusunu Yanıtla</h2><p>{selected.question}</p><label>Yanıt<textarea name="answer" required maxLength={2000} defaultValue={selected.answer || ""} /></label><div className="drawer-buttons"><button className="btn primary">Yanıtı Gönder</button><button type="button" className="btn" onClick={() => setSelected(null)}>Vazgeç</button></div></form></div>}</>;
}
