"use client";
import { PointerEvent, useEffect, useRef, useState } from "react";
import { SellerShowcase } from "./seller-showcase";
type Viewport="web"|"mobile";type Key="banner"|"promotion"|"products";type Item={key:Key;width:number;height:number};type Showcase={banner_url:string|null;mobile_banner_url:string|null;promotion_text:string|null;status:string;layout_payload?:Record<Viewport,Item[]>};
const defaults:Record<Viewport,Item[]>={web:[{key:"banner",width:100,height:220},{key:"promotion",width:100,height:96},{key:"products",width:100,height:260}],mobile:[{key:"banner",width:100,height:180},{key:"promotion",width:100,height:88},{key:"products",width:100,height:280}]};const labels:Record<Key,string>={banner:"Mağaza banneri",promotion:"Tanıtım alanı",products:"Ürün vitrini"};
export function SellerLayoutEditor(){const[data,setData]=useState<Showcase|null>(null),[viewport,setViewport]=useState<Viewport>("web"),[layout,setLayout]=useState<Record<Viewport,Item[]>>(defaults),[dragged,setDragged]=useState<Key|null>(null),[selected,setSelected]=useState<Key|null>(null),[message,setMessage]=useState("");const stageRef=useRef<HTMLDivElement>(null);const load=async()=>{const response=await fetch("/api/store-showcase"),result=await response.json();if(response.ok){setData(result.showcase);if(result.showcase?.layout_payload)setLayout(result.showcase.layout_payload)}};useEffect(()=>{void load()},[]);
function drop(target:Key){if(!dragged||dragged===target)return;setLayout(current=>{const list=[...current[viewport]],from=list.findIndex(item=>item.key===dragged),to=list.findIndex(item=>item.key===target),[moving]=list.splice(from,1);list.splice(to,0,moving);return{...current,[viewport]:list}});setDragged(null)}
function resize(event:PointerEvent<HTMLButtonElement>,key:Key){event.preventDefault();event.stopPropagation();const item=layout[viewport].find(value=>value.key===key),stage=stageRef.current;if(!item||!stage)return;const startX=event.clientX,startY=event.clientY,startWidth=item.width,startHeight=item.height,stageWidth=stage.clientWidth;const move=(next:globalThis.PointerEvent)=>setLayout(current=>({...current,[viewport]:current[viewport].map(value=>value.key===key?{...value,width:Math.max(40,Math.min(100,startWidth+(next.clientX-startX)/stageWidth*100)),height:Math.max(72,Math.min(640,startHeight+next.clientY-startY))}:value)}));const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop)}
async function save(){const response=await fetch("/api/store-showcase",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"showcase",bannerUrl:data?.banner_url||"",mobileBannerUrl:data?.mobile_banner_url||"",promotionText:data?.promotion_text||"",status:data?.status||"draft",layout:{web:layout.web.map(item=>({...item,width:Math.round(item.width),height:Math.round(item.height)})),mobile:layout.mobile.map(item=>({...item,width:Math.round(item.width),height:Math.round(item.height)}))}})}),result=await response.json();setMessage(response.ok?`${viewport==="web"?"Web":"Mobil"} mağaza düzeni kaydedildi.`:result.error)}
return <section className="visual-editor card"><div className="visual-editor-head"><div><h3>Görsel Mağaza Düzenleyici</h3><p>Banner, tanıtım ve ürün vitrininizi sürükleyerek yerleştirin ve ölçülendirin.</p></div><div className="visual-editor-actions"><div className="view-switch"><button className={viewport==="web"?"active":""} onClick={()=>setViewport("web")}><i className="fa-solid fa-display"/> Web</button><button className={viewport==="mobile"?"active":""} onClick={()=>setViewport("mobile")}><i className="fa-solid fa-mobile-screen"/> Mobil</button></div><button className="btn primary" onClick={()=>void save()}><i className="fa-solid fa-floppy-disk"/> Düzeni Kaydet</button></div></div>{message&&<div className="layout-message">{message}</div>}<div className={viewport==="mobile"?"layout-device phone":"layout-device desktop"}>{viewport==="mobile"&&<div className="phone-speaker"/>}<div className="layout-browser-bar"><span/><span/><span/><b>bişeyeksik mağaza</b></div><div className="layout-stage" ref={stageRef}>{layout[viewport].map(item=><article key={item.key} style={{width:`${item.width}%`,height:item.height}} className={`layout-block ${selected===item.key?"selected":""}`} draggable onDragStart={()=>setDragged(item.key)} onDragOver={event=>event.preventDefault()} onDrop={()=>drop(item.key)} onClick={()=>setSelected(item.key)}><div className="layout-drag"><i className="fa-solid fa-grip-vertical"/><span><b>{labels[item.key]}</b><small>{item.key==="banner"?(viewport==="web"?data?.banner_url||"Web banner seçilmedi":data?.mobile_banner_url||"Mobil banner seçilmedi"):item.key==="promotion"?data?.promotion_text||"Tanıtım metni":"Aktif mağaza ürünleri"}</small></span></div><div className="layout-placeholder"><i className={`fa-solid ${item.key==="banner"?"fa-image":item.key==="products"?"fa-bag-shopping":"fa-bullhorn"}`}/><span>{Math.round(item.width)}% × {Math.round(item.height)} px</span></div><button className="layout-resize" aria-label="Ölçülendir" onPointerDown={event=>resize(event,item.key)}><i className="fa-solid fa-up-right-and-down-left-from-center"/></button></article>)}</div></div></section>}
export function SellerShowcaseLayout(){return <><SellerShowcase mode="showcase"/><SellerLayoutEditor/></>}
