"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Document = { id:string; document_type:string; original_file_name:string; file_size:number; status:string; seller_note:string|null; admin_note:string|null; reviewed_at:string|null; created_at:string };
const names:Record<string,string>={tax_certificate:"Vergi Levhası",signature_circular:"İmza Sirküleri",iban_document:"IBAN Belgesi",authorized_identity:"Yetkili Kimlik",activity_certificate:"Faaliyet Belgesi",other:"Diğer"};
const labels:Record<string,string>={pending:"Bekliyor",under_review:"İnceleniyor",approved:"Onaylandı",missing:"Eksik",unreadable:"Okunmuyor"};

export function SellerDocuments(){
 const[items,setItems]=useState<Document[]>([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/documents"),result=await response.json();if(response.ok){setItems(result.documents||[]);setError("")}else setError(result.error||"Evraklar alınamadı.");setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const stats=useMemo(()=>({approved:items.filter(x=>x.status==="approved").length,review:items.filter(x=>["pending","under_review"].includes(x.status)).length,missing:items.filter(x=>["missing","unreadable"].includes(x.status)).length}),[items]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setUploading(true);setError("");setMessage("");const form=event.currentTarget,response=await fetch("/api/documents",{method:"POST",body:new FormData(form)}),result=await response.json();if(response.ok){form.reset();setMessage("Evrak inceleme kuyruğuna gönderildi.");await load()}else setError(result.error||"Evrak yüklenemedi.");setUploading(false)}
 return <><div className="page-head"><div className="page-title"><h1>Evraklarım <i className="fa-solid fa-circle-check seller-backend-check"/></h1><p>Mağaza evraklarınızı güvenli biçimde yükleyin ve değerlendirme durumlarını takip edin.</p></div></div>
 <div className="catalog-board"><article className="green"><i className="fa-solid fa-file-circle-check"/><h4>Onaylanan Evrak</h4><b>{stats.approved}</b><span>Güncel mağaza verisi</span></article><article className="yellow"><i className="fa-solid fa-clock"/><h4>İncelemede Belge</h4><b>{stats.review}</b><span>Güncel mağaza verisi</span></article><article className="red"><i className="fa-solid fa-file-circle-xmark"/><h4>Yeniden İstenen Belge</h4><b>{stats.missing}</b><span>Güncel mağaza verisi</span></article></div>
 <form className="card seller-form-card" onSubmit={upload}><div className="card-head"><h3>Evrak Yükle</h3><span className="link">PDF, JPG, PNG · En fazla 10 MB</span></div><div className="card-body form-grid"><label className="field">Evrak Türü<select name="documentType" required>{Object.entries(names).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field">Dosya<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label><label className="field wide">Açıklama<textarea name="note" maxLength={1000}/></label><div className="drawer-buttons"><button className="btn primary" disabled={uploading}>{uploading?"Yükleniyor":"Evrakı Gönder"}</button></div>{error&&<div className="admin-inline-error">{error}</div>}{message&&<div className="info-strip">{message}</div>}</div></form>
 <div className="card content-table"><div className="card-head"><h3>Evrak Durumları</h3><span className="link">{items.length} kayıt</span></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Evrak</th><th>Dosya</th><th>Yükleme</th><th>Durum</th><th>Admin Notu</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Evraklar yükleniyor...</td></tr>:items.length?items.map(item=><tr key={item.id}><td>{names[item.document_type]||item.document_type}</td><td>{item.original_file_name}<small>{Math.ceil(item.file_size/1024)} KB</small></td><td>{new Date(item.created_at).toLocaleString("tr-TR")}</td><td><span className={`pill ${item.status==="approved"?"green":item.status==="missing"||item.status==="unreadable"?"red":"yellow"}`}>{labels[item.status]||item.status}</span></td><td>{item.admin_note||"-"}</td></tr>):<tr><td colSpan={5}>Henüz evrak yüklenmedi.</td></tr>}</tbody></table></div></div></>;
}
