"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useSeller } from "./seller-shell";

type Item={id:string;productTitle:string;variantTitle:string;sellerSku:string;quantity:number;unitPrice:number;lineTotal:number;status:string};
type Order={id:string;number:string;status:string;paymentStatus:string;recipient:string;city:string;createdAt:string;total:number;items:Item[]};
const labels:Record<string,string>={created:"Ödeme Bekliyor",awaiting_payment:"Ödeme Bekliyor",paid:"Ödendi",preparing:"Hazırlanıyor",partially_shipped:"Kısmen Kargolandı",shipped:"Kargolandı",delivered:"Teslim Edildi",cancelled:"İptal",refunded:"İade"};
const money=(value:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(value);

export function SellerOrders({compact=false}:{compact?:boolean}){
 const{openDrawer,setActive}=useSeller(),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/orders"),result=await response.json();if(response.ok)setOrders(result.orders||[]);else setError(result.error||"Siparişler alınamadı.")}catch{setError("Siparişler alınamadı.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const visible=compact?orders.slice(0,3):orders;
 const stats=useMemo(()=>({total:orders.length,pending:orders.filter(order=>order.paymentStatus==="pending").length,paid:orders.filter(order=>order.paymentStatus==="paid").length,revenue:orders.filter(order=>order.paymentStatus==="paid").reduce((sum,order)=>sum+order.total,0)}),[orders]);
 if(compact)return <div className="card"><div className="card-head"><h3>Son Siparişler <i className="fa-solid fa-circle-check seller-backend-check"/></h3><button className="link" onClick={()=>setActive("orders")}>Tümünü Gör</button></div><OrderTable orders={visible} loading={loading} error={error} detail={number=>openDrawer({type:"order",record:number})}/></div>;
 const shipped=orders.filter(order=>order.status==="shipped"||order.status==="partially_shipped").length;
 const issues=orders.filter(order=>order.status==="cancelled"||order.status==="refunded").length;
 const download=()=>{const lines=[["Sipariş","Müşteri","Tutar","Durum"],...orders.map(x=>[x.number,x.recipient,String(x.total),labels[x.status]||x.status])];const blob=new Blob([lines.map(x=>x.join(";")).join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="siparisler.csv";a.click();URL.revokeObjectURL(url)};
 return <><div className="page-head"><div className="page-title"><h1>Sipariş / Kargo Yönetimi <i className="fa-solid fa-circle-check seller-backend-check"/></h1><p>Yeni, kargolanacak, teslim onayı bekleyen ve hakedişe aktarılacak siparişleri yönetin.</p></div><div className="head-actions"><button className="btn" onClick={()=>void load()}><i className="fa-solid fa-rotate"/> Yenile</button><button className="btn primary" onClick={download}><i className="fa-solid fa-download"/> İndir</button></div></div><div className="be-order-kpis"><div className="be-order-kpi"><small>Yeni / Ödeme Alındı</small><b>{stats.paid}</b><span>Kargolama bekliyor</span></div><div className="be-order-kpi"><small>Kargoda</small><b>{shipped}</b><span>Takipteki sipariş</span></div><div className="be-order-kpi"><small>Hakedişe Hazır</small><b>{money(stats.revenue)}</b><span>Aktarım bekleyen tutar</span></div><div className="be-order-kpi"><small>Sorunlu</small><b>{issues}</b><span>Destek/itiraz gerekli</span></div></div><div className="grid-2"><div className="card be-order-card"><div className="card-head"><h3>Sipariş Operasyon Listesi</h3><span className="link">Canlı GeT</span></div><OrderTable orders={visible} loading={loading} error={error} detail={number=>openDrawer({type:"order",record:number})}/></div><div className="card be-order-card"><div className="card-head"><h3>Kargolama Görevleri</h3><span className="link">Öncelikli</span></div><div className="card-body list">{orders.filter(x=>x.status==="paid"||x.status==="preparing").length?orders.filter(x=>x.status==="paid"||x.status==="preparing").map(x=><div className="row" key={x.id}><div><div className="row-title">{x.number}</div><div className="row-sub">{x.recipient} · {x.city}</div></div><button className="pill" onClick={()=>openDrawer({type:"order",record:x.number})}>Detay</button></div>):<p>Bekleyen kargolama görevi bulunmuyor.</p>}</div></div></div><div className="grid-2"><div className="card be-order-card"><div className="card-head"><h3>Hakediş Durumu</h3><span className="link">Finans Bağlantılı</span></div><div className="card-body"><strong>{money(stats.revenue)}</strong><p>Ödemesi alınan siparişlerin brüt mağaza tutarı.</p></div></div><div className="card be-order-card"><div className="card-head"><h3>Sipariş İşlem Geçmişi</h3><span className="link">Son kayıtlar</span></div><div className="card-body list">{orders.slice(0,4).map(x=><div className="row" key={x.id}><div><div className="row-title">{x.number}</div><div className="row-sub">{new Date(x.createdAt).toLocaleString("tr-TR")}</div></div><span className="pill blue">{labels[x.status]||x.status}</span></div>)}</div></div></div></>;
}

function OrderTable({orders,loading,error,detail}:{orders:Order[];loading:boolean;error:string;detail:(number:string)=>void}){return <div className="card-body table-scroll"><table className="table"><thead><tr><th>Sipariş</th><th>Müşteri</th><th>Ürün</th><th>Tutar</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Siparişler yükleniyor...</td></tr>:error?<tr><td colSpan={6}>{error}</td></tr>:orders.length?orders.map(order=><tr key={order.id}><td><strong>{order.number}</strong><small className="seller-order-date">{new Date(order.createdAt).toLocaleString("tr-TR")}</small></td><td>{order.recipient}<small className="seller-order-date">{order.city}</small></td><td>{order.items.reduce((sum,item)=>sum+item.quantity,0)} adet</td><td>{money(order.total)}</td><td><span className={`pill ${order.paymentStatus==="paid"?"green":"yellow"}`}>{labels[order.status]||order.status}</span></td><td className="seller-actions"><button onClick={()=>detail(order.number)}>Detay</button></td></tr>):<tr><td colSpan={6}>Henüz sipariş bulunmuyor.</td></tr>}</tbody></table></div>}
