"use client";
import {useEffect,useMemo,useState} from "react";
type Entry={id:string;entry_type:string;amount:number;currency:string;description:string;available_at:string;created_at:string;orders:{order_number:string}|null;order_items:{product_title:string}|null};
type Settlement={id:string;period_start:string;period_end:string;gross_amount:number;deduction_amount:number;net_amount:number;status:string};
const labels:Record<string,string>={sale:"Satış",commission:"Komisyon",service_fee:"Hizmet Bedeli",refund:"İade",adjustment:"Düzeltme",settlement:"Hakediş"};
const money=(value:number,currency="TRY")=>Number(value).toLocaleString("tr-TR",{style:"currency",currency});
export function SellerFinance(){
 const[ledger,setLedger]=useState<Entry[]>([]),[settlements,setSettlements]=useState<Settlement[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void fetch("/api/finance").then(async response=>{const result=await response.json();if(response.ok){setLedger(result.ledger||[]);setSettlements(result.settlements||[])}else setError(result.error)}).finally(()=>setLoading(false))},[]);
 const totals=useMemo(()=>({gross:ledger.filter(x=>x.amount>0).reduce((n,x)=>n+Number(x.amount),0),deductions:Math.abs(ledger.filter(x=>x.amount<0).reduce((n,x)=>n+Number(x.amount),0)),available:ledger.filter(x=>new Date(x.available_at)<=new Date()).reduce((n,x)=>n+Number(x.amount),0)}),[ledger]);
 const download=()=>{const rows=[["Tarih","Açıklama","Tutar"],...ledger.map(x=>[x.created_at,x.description,String(x.amount)])],url=URL.createObjectURL(new Blob([rows.map(x=>x.join(";")).join("\n")],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="finans-ozeti.csv";a.click();URL.revokeObjectURL(url)};
 return <><div className="page-head"><div className="page-title"><h1>Finans / Hakedişlerim <i className="fa-solid fa-circle-check seller-backend-check"/></h1><p>Hakediş, komisyon, iade kesintisi, sipariş farkları ve ödeme takvimi.</p></div><div className="head-actions"><button className="btn" onClick={()=>document.getElementById("seller-finance-movements")?.scrollIntoView({behavior:"smooth"})}><i className="fa-solid fa-circle-info"/> Detay</button><button className="btn" onClick={download}><i className="fa-solid fa-download"/> Özet İndir</button></div></div>
 <div className="be-finance-kpis"><div className="be-finance-kpi green"><small>Net Hakediş</small><b>{money(totals.available)}</b><span>Kullanılabilir bakiye</span></div><div className="be-finance-kpi"><small>Brüt Satış</small><b>{money(totals.gross)}</b><span>Toplam pozitif hareket</span></div><div className="be-finance-kpi red"><small>İade / Kesinti</small><b>{money(totals.deductions)}</b><span>Komisyon ve kesintiler</span></div><div className="be-finance-kpi yellow"><small>Hakediş Dönemi</small><b>{settlements.length}</b><span>Kayıtlı ödeme dönemi</span></div></div>{error&&<div className="admin-inline-error">{error}</div>}
 <div className="be-seller-finance-summary"><div className="be-finance-panel"><h3>Hakediş Hesap Özeti</h3><div className="be-money-line"><span>Brüt satış</span><b>{money(totals.gross)}</b></div><div className="be-money-line"><span>Kesintiler</span><b>-{money(totals.deductions)}</b></div><div className="be-money-line total"><span>Net hakediş</span><b>{money(totals.available)}</b></div></div><div className="be-finance-panel"><h3>Komisyon Bilgilerim</h3><p>Komisyon, hizmet bedeli ve iade kesintileri sipariş bazında aşağıdaki hareketlerde gösterilir.</p></div></div>
 <div className="card content-table be-finance-card"><div className="card-head"><h3>Hakediş ve Ödeme Takvimi</h3><span className="link">GeT / teslim onayı sonrası</span></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Dönem</th><th>Brüt</th><th>Kesinti</th><th>Net</th><th>Durum</th></tr></thead><tbody>{settlements.length?settlements.map(x=><tr key={x.id}><td>{x.period_start} / {x.period_end}</td><td>{money(x.gross_amount)}</td><td>{money(x.deduction_amount)}</td><td><b>{money(x.net_amount)}</b></td><td><span className="pill yellow">{x.status}</span></td></tr>):<tr><td colSpan={5}>Hakediş kaydı bulunmuyor.</td></tr>}</tbody></table></div></div>
 <div className="card content-table be-finance-card" id="seller-finance-movements"><div className="card-head"><h3>Hareketler</h3></div><div className="card-body table-scroll"><table className="table"><thead><tr><th>Tarih</th><th>Sipariş / Ürün</th><th>Hareket</th><th>Kullanılabilir</th><th>Tutar</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Yükleniyor...</td></tr>:ledger.length?ledger.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleDateString("tr-TR")}</td><td>{x.orders?.order_number||"-"}<div className="row-sub">{x.order_items?.product_title||x.description}</div></td><td>{labels[x.entry_type]||x.entry_type}</td><td>{new Date(x.available_at).toLocaleDateString("tr-TR")}</td><td><b className={x.amount<0?"text-danger":""}>{money(x.amount,x.currency)}</b></td></tr>):<tr><td colSpan={5}>Finans hareketi bulunmuyor.</td></tr>}</tbody></table></div></div></>;
}
