"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useStore } from "@/components/store-provider";
import { formatTL } from "@/data/catalog";

type Address={id:string;title:string;recipient_name:string;city:string;district:string;address_line:string;is_default:boolean};

export default function Checkout(){
 const{cart}=useStore(),router=useRouter(),[addresses,setAddresses]=useState<Address[]>([]),[addressId,setAddressId]=useState(""),[agree,setAgree]=useState(false),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[error,setError]=useState("");
 const checkoutKey=useRef(crypto.randomUUID());
 const selected=useMemo(()=>cart.filter(item=>item.selected),[cart]);
 const total=selected.reduce((sum,item)=>sum+item.product.price*item.quantity,0);
 useEffect(()=>{void fetch("/api/customer/addresses").then(async response=>{if(response.status===401){router.replace("/giris?next=/odeme");return}const result=await response.json();if(!response.ok){setError(result.error||"Adresler alınamadı.");return}const items:Address[]=result.addresses||[];setAddresses(items);setAddressId(items.find(item=>item.is_default)?.id||items[0]?.id||"")}).catch(()=>setError("Adresler alınamadı.")).finally(()=>setLoading(false))},[router]);
 async function submit(event:FormEvent){event.preventDefault();if(!addressId){setError("Teslimat adresi seçmelisiniz.");return}if(!agree){setError("Devam etmek için sözleşmeleri onaylamalısınız.");return}if(!selected.length){setError("Sipariş oluşturulacak seçili ürün bulunmuyor.");return}setSubmitting(true);setError("");let couponCode:string|undefined;try{couponCode=JSON.parse(sessionStorage.getItem("bx-valid-coupon")||"null")?.code}catch{}const response=await fetch("/api/customer/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({addressId,checkoutKey:checkoutKey.current,couponCode})}),result=await response.json();if(response.status===401){router.replace("/giris?next=/odeme");return}if(!response.ok){setError(result.error||"Sipariş oluşturulamadı.");setSubmitting(false);return}sessionStorage.removeItem("bx-valid-coupon");router.replace(`/hesabim?tab=orders&order=${encodeURIComponent(result.order.order_number)}`);router.refresh()}
 return <div className="container page checkout"><div className="checkout-steps"><span className="done">✓ Sepet</span><span className="active">2 Adres</span><span>3 Sipariş</span></div><form onSubmit={submit}><section><div className="checkout-panel"><h2>Teslimat Adresi</h2>{loading?<p>Adresler yükleniyor...</p>:addresses.length?<div className="address-list">{addresses.map(address=><button type="button" className={addressId===address.id?"selected":""} onClick={()=>setAddressId(address.id)} key={address.id}><strong>{address.title}</strong><span>{address.recipient_name}</span><p>{address.address_line}<br/>{address.district} / {address.city}</p></button>)}</div>:<div className="checkout-address-empty"><p>Sipariş verebilmek için teslimat adresi eklemelisiniz.</p><Link href="/hesabim?tab=addresses"><i className="fa-solid fa-plus"/> Adres Ekle</Link></div>}</div><div className="checkout-panel checkout-payment-pending"><h2>Sipariş Durumu</h2><div><i className="fa-solid fa-clock"/><span><strong>Ödeme bekleyen sipariş</strong><p>Siparişiniz oluşturulduktan sonra ödeme durumu hesabınızdan takip edilir.</p></span></div><label className="agreement"><input type="checkbox" checked={agree} onChange={event=>setAgree(event.target.checked)}/> Ön bilgilendirme formunu ve mesafeli satış sözleşmesini okudum.</label></div></section><aside className="summary checkout-summary"><h2>Sipariş Özeti</h2><p>{selected.reduce((sum,item)=>sum+item.quantity,0)} ürün <strong>{formatTL(total)}</strong></p><p>Kargo <strong>Ücretsiz</strong></p><hr/><p className="total">Toplam <strong>{formatTL(total)}</strong></p><button disabled={submitting||loading||!addresses.length||!selected.length}>{submitting?"Sipariş oluşturuluyor":"Siparişi Oluştur"}</button><small><i className="fa-solid fa-shield-halved"/> Sipariş ve stok işlemleri güvenli şekilde kaydedilir.</small>{error&&<div className="customer-auth-message">{error}</div>}</aside></form></div>;
}
